# Generated by Django 4.2.4 on 2023-10-04 02:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceMaintence',
            new_name='ProductMaintenance',
        ),
        migrations.RenameModel(
            old_name='ProductMaintence',
            new_name='ServiceMaintenance',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='workstation_fk',
        ),
        migrations.RemoveField(
            model_name='productmaintenance',
            name='service_fk',
        ),
        migrations.RemoveField(
            model_name='servicemaintenance',
            name='product_fk',
        ),
        migrations.AddField(
            model_name='payment',
            name='reserve_fk',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Main.reserve'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmaintenance',
            name='product_fk',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemaintenance',
            name='service_fk',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Main.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workstation',
            name='name',
            field=models.CharField(choices=[('workstation1', 'WORKSTATION 1'), ('workstation2', 'WORKSTATION 2')], max_length=200),
        ),
    ]
