# Generated by Django 4.2.4 on 2023-10-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productmaintenance',
            name='unit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
